"""Adicionando coluna nome_administrador

Revision ID: 5310b18f5a44
Revises: f49b43c1d544
Create Date: 2024-11-21 09:53:23.955521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5310b18f5a44'
down_revision = 'f49b43c1d544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_administrador', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.drop_column('nome_administrador')

    # ### end Alembic commands ###
