"""Adiciona link_incluso à tabela monitorias

Revision ID: 7423f8ada875
Revises: dedb567e8796
Create Date: 2024-11-19 13:01:13.373252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7423f8ada875'
down_revision = 'dedb567e8796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_incluso', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.drop_column('link_incluso')

    # ### end Alembic commands ###
