"""empty message

Revision ID: dedb567e8796
Revises: 
Create Date: 2024-11-08 16:44:50.041763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dedb567e8796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('grupo', sa.String(length=20), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('monitoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_analista', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=100), nullable=False),
    sa.Column('id_atendimento', sa.String(length=100), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('descritivo', sa.Text(), nullable=True),
    sa.Column('arquivo_pdf', sa.String(length=200), nullable=True),
    sa.Column('gravacao', sa.String(length=200), nullable=True),
    sa.Column('penalidades', sa.Text(), nullable=True),
    sa.Column('data_monitoria', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('assinatura', sa.String(length=100), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitoria')
    op.drop_table('usuario')
    # ### end Alembic commands ###
