"""Criando tabelas iniciais

Revision ID: eeff95143ceb
Revises: 
Create Date: 2024-10-31 14:26:57.620685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeff95143ceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.drop_column('horario_assinatura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_assinatura', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
