"""Adicionando novas colunas de pontuação à tabela monitoria

Revision ID: f49b43c1d544
Revises: 7423f8ada875
Create Date: 2024-11-20 13:13:04.760942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49b43c1d544'
down_revision = '7423f8ada875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('se_apresentou', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atendeu_prontidao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ouviu_demanda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('demonstrou_empatia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('realizou_sondagem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('argumentou_cancelamento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('respeitou_cliente', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmacao_cadastral', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('contornou_odc', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seguiu_procedimentos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoria', schema=None) as batch_op:
        batch_op.drop_column('seguiu_procedimentos')
        batch_op.drop_column('contornou_odc')
        batch_op.drop_column('confirmacao_cadastral')
        batch_op.drop_column('respeitou_cliente')
        batch_op.drop_column('argumentou_cancelamento')
        batch_op.drop_column('realizou_sondagem')
        batch_op.drop_column('demonstrou_empatia')
        batch_op.drop_column('ouviu_demanda')
        batch_op.drop_column('atendeu_prontidao')
        batch_op.drop_column('se_apresentou')

    # ### end Alembic commands ###
